export type CorporateStatus = "Verified" | "Pending" | "Incomplete";

export interface Corporate {
  name: string;
  phone: string;
  email: string;
  status: CorporateStatus;
  imageUrl: string;
}

export const corporates: Corporate[] = [
  {
    name: "Barone LLC",
    phone: "+435802654",
    email: "jonet@gmail.com",
    status: "Verified",
    imageUrl: "https://picsum.photos/40/40?random=1",
  },
  {
    name: "Blanford Ltd.",
    phone: "+435802654",
    email: "jonet@gmail.com",
    status: "Pending",
    imageUrl: "https://picsum.photos/40/40?random=2",
  },
  {
    name: "Abastergo Ltd.",
    phone: "+435802654",
    email: "jonet@gmail.com",
    status: "Pending",
    imageUrl: "https://picsum.photos/40/40?random=3",
  },
  {
    name: "Blanford Ltd.",
    phone: "+435802654",
    email: "jonet@gmail.com",
    status: "Verified",
    imageUrl: "https://picsum.photos/40/40?random=4",
  },
  {
    name: "Acme Co.",
    phone: "+435802654",
    email: "jonet@gmail.com",
    status: "Incomplete",
    imageUrl: "https://picsum.photos/40/40?random=5",
  },
  {
    name: "Blanford Ltd.",
    phone: "+435802654",
    email: "jonet@gmail.com",
    status: "Verified",
    imageUrl: "https://picsum.photos/40/40?random=6",
  },
  {
    name: "Blifco Enterprises Ltd.",
    phone: "+435802654",
    email: "jonet@gmail.com",
    status: "Verified",
    imageUrl: "https://picsum.photos/40/40?random=7",
  },
  {
    name: "Big Kahuna Burger Ltd.",
    phone: "+435802654",
    email: "jonet@gmail.com",
    status: "Verified",
    imageUrl: "https://picsum.photos/40/40?random=8",
  },
  {
    name: "Barone LLC",
    phone: "+435802654",
    email: "jonet@gmail.com",
    status: "Verified",
    imageUrl: "https://picsum.photos/40/40?random=1",
  },
  {
    name: "Blanford Ltd.",
    phone: "+435802654",
    email: "jonet@gmail.com",
    status: "Pending",
    imageUrl: "https://picsum.photos/40/40?random=2",
  },
  {
    name: "Abastergo Ltd.",
    phone: "+435802654",
    email: "jonet@gmail.com",
    status: "Pending",
    imageUrl: "https://picsum.photos/40/40?random=3",
  },
  {
    name: "Blanford Ltd.",
    phone: "+435802654",
    email: "jonet@gmail.com",
    status: "Verified",
    imageUrl: "https://picsum.photos/40/40?random=4",
  },
  {
    name: "Acme Co.",
    phone: "+435802654",
    email: "jonet@gmail.com",
    status: "Incomplete",
    imageUrl: "https://picsum.photos/40/40?random=5",
  },
  {
    name: "Blanford Ltd.",
    phone: "+435802654",
    email: "jonet@gmail.com",
    status: "Verified",
    imageUrl: "https://picsum.photos/40/40?random=6",
  },
  {
    name: "Blifco Enterprises Ltd.",
    phone: "+435802654",
    email: "jonet@gmail.com",
    status: "Verified",
    imageUrl: "https://picsum.photos/40/40?random=7",
  },
  {
    name: "Big Kahuna Burger Ltd.",
    phone: "+435802654",
    email: "jonet@gmail.com",
    status: "Verified",
    imageUrl: "https://picsum.photos/40/40?random=8",
  },
  {
    name: "Barone LLC",
    phone: "+435802654",
    email: "jonet@gmail.com",
    status: "Verified",
    imageUrl: "https://picsum.photos/40/40?random=1",
  },
  {
    name: "Blanford Ltd.",
    phone: "+435802654",
    email: "jonet@gmail.com",
    status: "Pending",
    imageUrl: "https://picsum.photos/40/40?random=2",
  },
  {
    name: "Abastergo Ltd.",
    phone: "+435802654",
    email: "jonet@gmail.com",
    status: "Pending",
    imageUrl: "https://picsum.photos/40/40?random=3",
  },
  {
    name: "Blanford Ltd.",
    phone: "+435802654",
    email: "jonet@gmail.com",
    status: "Verified",
    imageUrl: "https://picsum.photos/40/40?random=4",
  },
  {
    name: "Acme Co.",
    phone: "+435802654",
    email: "jonet@gmail.com",
    status: "Incomplete",
    imageUrl: "https://picsum.photos/40/40?random=5",
  },
  {
    name: "Blanford Ltd.",
    phone: "+435802654",
    email: "jonet@gmail.com",
    status: "Verified",
    imageUrl: "https://picsum.photos/40/40?random=6",
  },
  {
    name: "Blifco Enterprises Ltd.",
    phone: "+435802654",
    email: "jonet@gmail.com",
    status: "Verified",
    imageUrl: "https://picsum.photos/40/40?random=7",
  },
  {
    name: "Big Kahuna Burger Ltd.",
    phone: "+435802654",
    email: "jonet@gmail.com",
    status: "Verified",
    imageUrl: "https://picsum.photos/40/40?random=8",
  },
  {
    name: "Barone LLC",
    phone: "+435802654",
    email: "jonet@gmail.com",
    status: "Verified",
    imageUrl: "https://picsum.photos/40/40?random=1",
  },
  {
    name: "Blanford Ltd.",
    phone: "+435802654",
    email: "jonet@gmail.com",
    status: "Pending",
    imageUrl: "https://picsum.photos/40/40?random=2",
  },
  {
    name: "Abastergo Ltd.",
    phone: "+435802654",
    email: "jonet@gmail.com",
    status: "Pending",
    imageUrl: "https://picsum.photos/40/40?random=3",
  },
  {
    name: "Blanford Ltd.",
    phone: "+435802654",
    email: "jonet@gmail.com",
    status: "Verified",
    imageUrl: "https://picsum.photos/40/40?random=4",
  },
  {
    name: "Acme Co.",
    phone: "+435802654",
    email: "jonet@gmail.com",
    status: "Incomplete",
    imageUrl: "https://picsum.photos/40/40?random=5",
  },
  {
    name: "Blanford Ltd.",
    phone: "+435802654",
    email: "jonet@gmail.com",
    status: "Verified",
    imageUrl: "https://picsum.photos/40/40?random=6",
  },
  {
    name: "Blifco Enterprises Ltd.",
    phone: "+435802654",
    email: "jonet@gmail.com",
    status: "Verified",
    imageUrl: "https://picsum.photos/40/40?random=7",
  },
  {
    name: "Big Kahuna Burger Ltd.",
    phone: "+435802654",
    email: "jonet@gmail.com",
    status: "Verified",
    imageUrl: "https://picsum.photos/40/40?random=8",
  },
];
